#include<stdio.h>
int main()
{
    int n,i,arr[100],s=0;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%d",&arr[i]);
    }
    for(i=0;i<n;i++)
    {
        if(arr[i]%2==0)
        {
            if(i%2==0)
            {
                s++;
            }
            else
            {
                printf("False");
                s=0;
                break;
            }
        }
    }
    if(s>0)
    {
        printf("True");
    }
}